Added event title styling to Event component
HackMelbourne/HackMelbourne.github.io pull request #67
Opened 2023-12-16 13:02 UTC by vjy02

Let me know of any issues.

2023-12-19 00:52 UTC, e3lo requested changes
Looks really nice just update the stroke width and props

2023-12-19 00:52 UTC, e3lo commented on src/routes/Events.tsx
> +            WebkitTextStrokeWidth: '1px',
Change text stroke to be 2px on md screen sizes and 1px on mobile

2023-12-19 00:52 UTC, e3lo commented on src/routes/Events.tsx
> +            Events / Initiatives
Extract all text as props

2023-12-20 13:43 UTC, vjy02 commented
@e3lo I updated the text as props but have it inside main.tsx atm, not sure if that is good or is it fine to just be there for now?

2023-12-22 04:58 UTC, e3lo commented
@vjy02 Oops I didn't realise, move the event title code into a new folder in features so it should be src/features/TitleHero/TitleHero.tsx
Then in Events.tsx import TitleHero and use it.

Essentially Events.tsx is the new root.tsx for the events page

2023-12-22 10:18 UTC, vjy02 commented
@e3lo All done lmk if it needs any more changes

2023-12-30 01:48 UTC, e3lo approved these changes

2023-12-30 01:49 UTC, merged